influxdb:
  #build: .
  image: yongjhih/influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
  #environment:
  volumes_from:
    - influxdb-data

influxdb-data:
  #build: .
  image: yongjhih/influxdb
  volumes:
    - /data
  command: /bin/true

grafana:
  image: grafana/grafana
  ports:
    - "3000:3000"
  environment:
    GF_SERVER_ROOT_URL: $GF_SERVER_ROOT_URL # "http://grafana.server.name"
    GF_SECURITY_ADMIN_PASSWORD: $GF_SECURITY_ADMIN_PASSWORD
  volumes_from:
    - grafana-data

grafana-data:
  image: grafana/grafana
  volumes:
    - /var/lib/grafana
  command: /bin/true

# vim:set et ts=2 sw=2:
