influxdb:
  build: .
  #image: yongjhih/influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
  environment:
    #ADMIN_USER: $INFLUXDB_ADMIN_USER
    #INFLUXDB_INIT_PWD: $INFLUXDB_INIT_PASSWORD
    #PRE_CREATE_DB: $INFLUXDB_PRE_CREATE_DB # "db1;db2;db3"
    ADMIN_USER: admin
    INFLUXDB_INIT_PWD: admin
    PRE_CREATE_DB: db1;db2;db3
  volumes_from:
    - influxdb-data

influxdb-data:
  build: .
  #image: yongjhih/influxdb
  volumes:
    - /data
  command: /bin/true

grafana:
  image: grafana/grafana:2.6.0
  ports:
    - "3000:3000"
  environment:
    GF_SERVER_ROOT_URL: $GF_SERVER_ROOT_URL # "http://grafana.server.name"
    GF_SECURITY_ADMIN_PASSWORD: $GF_SECURITY_ADMIN_PASSWORD
  volumes_from:
    - grafana-data
  links:
    - influxdb

grafana-data:
  image: grafana/grafana:2.6.0
  volumes:
    - /var/lib/grafana
  command: /bin/true

# vim:set et ts=2 sw=2:
